<?php
$a=997.48;
$FACTURE= rand(500000000,600000000) ;
$COMMANDE = rand(1000000000,100000000) ;
$CLIENT = rand(20000000,900000000)  ;
$Nom="Kenzo Marta";
$ADRESSE1="1 Avenue Pole Sidou";
$ADRESSE2="66000 Perpignan - France";
$Reference="IP-K5442/AE";
$Designation="Apple Iphone 11 Pro Gris Sideral 256G0  ";
$Taxe=0.00;  //TaxeDEA
$EcoTaxe=0.02; //EcoTaxeHT
$TaxeRCP=20; //TaxeRCP HT 
$PUHT=992.01;    //PU HT
$Montant =$a ;
$MontantTVA = 997.48;
$PUTTC= $Montant; //PUTTC
$Montant=$PUTTC; // Montant Total TTC |
$Qte=1;  //QTE
$CodeTVA=1; //CodeTVA
$IMEI="S/N IMEIL 35391510578613"; // S/N IMEIL
$TVA="20%"; // Code TVA 
$TotalHT=$PUHT;//Total HT
$TotalTTC=$Montant-$EcoTaxe;


?>

<!DOCTYPE HTML>
<html>
<head>
	<meta charset="utf-8">
<link rel="stylesheet" type="text/css" href="style.css"/>
</head>
<body>
<img style="position:absolute;top:2.89in;left:0.39in;width:1.17in;height:0.37in" src="OutDocument/ci_1.png" />
<div style="position:absolute;top:2.94in;left:0.46in;width:1.06in;line-height:0.14in;"><span style="font-style:normal;font-weight:bold;font-size:8pt;font-family:Helvetica;color:#000000">Référence
 Interne</span><span style="font-style:normal;font-weight:bold;font-size:8pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<img style="position:absolute;top:2.89in;left:1.56in;width:2.85in;height:0.37in" src="OutDocument/ci_2.png" />
<div style="position:absolute;top:2.94in;left:1.59in;width:0.73in;line-height:0.14in;"><span style="font-style:normal;font-weight:bold;font-size:8pt;font-family:Helvetica;color:#000000">Désignation</span><span style="font-style:normal;font-weight:bold;font-size:8pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<img style="position:absolute;top:2.89in;left:4.41in;width:0.39in;height:0.37in" src="OutDocument/ci_3.png" />
<div style="position:absolute;top:2.94in;left:4.45in;width:0.31in;line-height:0.14in;"><span style="font-style:normal;font-weight:bold;font-size:8pt;font-family:Helvetica;color:#000000">Taxe</span><span style="font-style:normal;font-weight:bold;font-size:8pt;font-family:Helvetica;color:#000000"> </span><br/><DIV style="position:relative; left:0.02in;"><span style="font-style:normal;font-weight:bold;font-size:8pt;font-family:Helvetica;color:#000000">DEA</span><span style="font-style:normal;font-weight:bold;font-size:8pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></DIV></div>
<img style="position:absolute;top:2.89in;left:4.80in;width:0.58in;height:0.37in" src="OutDocument/ci_4.png" />
<div style="position:absolute;top:2.94in;left:4.83in;width:0.53in;line-height:0.14in;"><span style="font-style:normal;font-weight:bold;font-size:8pt;font-family:Helvetica;color:#000000">EcoTaxe</span><span style="font-style:normal;font-weight:bold;font-size:8pt;font-family:Helvetica;color:#000000"> </span><br/><DIV style="position:relative; left:0.18in;"><span style="font-style:normal;font-weight:bold;font-size:8pt;font-family:Helvetica;color:#000000">HT</span><span style="font-style:normal;font-weight:bold;font-size:8pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></DIV></div>
<img style="position:absolute;top:2.89in;left:5.38in;width:0.64in;height:0.37in" src="OutDocument/ci_5.png" />
<div style="position:absolute;top:2.94in;left:5.48in;width:0.48in;line-height:0.14in;"><DIV style="position:relative; left:0.06in;"><span style="font-style:normal;font-weight:bold;font-size:8pt;font-family:Helvetica;color:#000000">Taxe </span><span style="font-style:normal;font-weight:bold;font-size:8pt;font-family:Helvetica;color:#000000"> </span><br/></DIV><span style="font-style:normal;font-weight:bold;font-size:8pt;font-family:Helvetica;color:#000000">RCP HT</span><span style="font-style:normal;font-weight:bold;font-size:8pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<img style="position:absolute;top:2.89in;left:6.02in;width:0.56in;height:0.37in" src="OutDocument/ci_6.png" />
<div style="position:absolute;top:2.94in;left:6.09in;width:0.46in;line-height:0.14in;"><span style="font-style:normal;font-weight:bold;font-size:8pt;font-family:Helvetica;color:#000000">P.U. HT</span><span style="font-style:normal;font-weight:bold;font-size:8pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<img style="position:absolute;top:2.89in;left:6.58in;width:0.62in;height:0.37in" src="OutDocument/ci_7.png" />
<div style="position:absolute;top:2.94in;left:6.64in;width:0.54in;line-height:0.14in;"><span style="font-style:normal;font-weight:bold;font-size:8pt;font-family:Helvetica;color:#000000">P.U. TTC</span><span style="font-style:normal;font-weight:bold;font-size:8pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<img style="position:absolute;top:2.89in;left:7.20in;width:0.39in;height:0.37in" src="OutDocument/ci_8.png" />
<div style="position:absolute;top:2.94in;left:7.30in;width:0.24in;line-height:0.14in;"><span style="font-style:normal;font-weight:bold;font-size:8pt;font-family:Helvetica;color:#000000">Qté</span><span style="font-style:normal;font-weight:bold;font-size:8pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<img style="position:absolute;top:2.89in;left:7.59in;width:0.50in;height:0.37in" src="OutDocument/ci_9.png" />
<div style="position:absolute;top:2.94in;left:7.67in;width:0.34in;line-height:0.14in;"><span style="font-style:normal;font-weight:bold;font-size:8pt;font-family:Helvetica;color:#000000">Code</span><span style="font-style:normal;font-weight:bold;font-size:8pt;font-family:Helvetica;color:#000000"> </span><br/><DIV style="position:relative; left:0.05in;"><span style="font-style:normal;font-weight:bold;font-size:8pt;font-family:Helvetica;color:#000000">TVA</span><span style="font-style:normal;font-weight:bold;font-size:8pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></DIV></div>
<img style="position:absolute;top:2.89in;left:8.09in;width:0.66in;height:0.37in" src="OutDocument/ci_10.png" />
<div style="position:absolute;top:2.94in;left:8.15in;width:0.59in;line-height:0.14in;"><DIV style="position:relative; left:0.02in;"><span style="font-style:normal;font-weight:bold;font-size:8pt;font-family:Helvetica;color:#000000">Montant</span><span style="font-style:normal;font-weight:bold;font-size:8pt;font-family:Helvetica;color:#000000"> </span><br/></DIV><span style="font-style:normal;font-weight:bold;font-size:8pt;font-family:Helvetica;color:#000000">Total TTC</span><span style="font-style:normal;font-weight:bold;font-size:8pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<img style="position:absolute;top:3.26in;left:0.39in;width:1.17in;height:0.30in" src="OutDocument/ci_11.png" />
<div style="position:absolute;top:3.31in;left:0.42in;width:0.81in;line-height:0.12in;"><span style="font-style:normal;font-weight:normal;font-size:7pt;font-family:Helvetica;color:#000000">
	<?php echo $Reference; ?></span><span style="font-style:normal;font-weight:normal;font-size:7pt;font-family:Helvetica;color:#000000"> </span><br/><span style="font-style:normal;font-weight:normal;font-size:7pt;font-family:Helvetica;color:#000000"></span><span style="font-style:normal;font-weight:normal;font-size:7pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<img style="position:absolute;top:3.26in;left:1.56in;width:2.85in;height:0.30in" src="OutDocument/ci_12.png" />
<div style="position:absolute;top:3.26in;left:1.59in;width:1.89in;line-height:0.12in;"><span style="font-style:normal;font-weight:normal;font-size:7pt;font-family:Helvetica;color:#000000">
	<?php echo $Designation;?></span><span style="font-style:normal;font-weight:normal;font-size:7pt;font-family:Helvetica;color:#000000"> </span><br/><span style="font-style:normal;font-weight:normal;font-size:7pt;font-family:Helvetica;color:#000000"><?php echo $IMEI;?></span><span style="font-style:normal;font-weight:normal;font-size:7pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<img style="position:absolute;top:3.26in;left:4.41in;width:0.39in;height:0.30in" src="OutDocument/ci_13.png" />
<div style="position:absolute;top:3.31in;left:4.56in;width:0.24in;line-height:0.12in;"><span style="font-style:normal;font-weight:normal;font-size:7pt;font-family:Helvetica;color:#000000">
	<?php echo $Taxe;?></span><span style="font-style:normal;font-weight:normal;font-size:7pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<img style="position:absolute;top:3.26in;left:4.80in;width:0.58in;height:0.30in" src="OutDocument/ci_14.png" />
<div style="position:absolute;top:3.31in;left:5.14in;width:0.24in;line-height:0.12in;"><span style="font-style:normal;font-weight:normal;font-size:7pt;font-family:Helvetica;color:#000000"><?php echo $EcoTaxe;?></span><span style="font-style:normal;font-weight:normal;font-size:7pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<img style="position:absolute;top:3.26in;left:5.38in;width:0.64in;height:0.30in" src="OutDocument/ci_15.png" />
<div style="position:absolute;top:3.31in;left:5.57in;width:0.29in;line-height:0.12in;"><span style="font-style:normal;font-weight:normal;font-size:7pt;font-family:Helvetica;color:#000000"><?php echo $TaxeRCP;?></span><span style="font-style:normal;font-weight:normal;font-size:7pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<img style="position:absolute;top:3.26in;left:6.02in;width:0.56in;height:0.30in" src="OutDocument/ci_16.png" />
<div style="position:absolute;top:3.31in;left:6.13in;width:0.35in;line-height:0.12in;"><span style="font-style:normal;font-weight:normal;font-size:7pt;font-family:Helvetica;color:#000000"><?php echo $PUHT;?></span><span style="font-style:normal;font-weight:normal;font-size:7pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<img style="position:absolute;top:3.26in;left:6.58in;width:0.62in;height:0.30in" src="OutDocument/ci_17.png" />
<div style="position:absolute;top:3.31in;left:6.80in;width:0.35in;line-height:0.12in;"><span style="font-style:normal;font-weight:normal;font-size:7pt;font-family:Helvetica;color:#000000"><?php echo $PUTTC;?></span><span style="font-style:normal;font-weight:normal;font-size:7pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<img style="position:absolute;top:3.26in;left:7.20in;width:0.39in;height:0.30in" src="OutDocument/ci_18.png" />
<div style="position:absolute;top:3.31in;left:7.50in;width:0.09in;line-height:0.12in;"><span style="font-style:normal;font-weight:normal;font-size:7pt;font-family:Helvetica;color:#000000"><?php echo $Qte;?></span><span style="font-style:normal;font-weight:normal;font-size:7pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<img style="position:absolute;top:3.26in;left:7.59in;width:0.50in;height:0.30in" src="OutDocument/ci_19.png" />
<div style="position:absolute;top:3.31in;left:8.00in;width:0.09in;line-height:0.12in;"><span style="font-style:normal;font-weight:normal;font-size:7pt;font-family:Helvetica;color:#000000"><?php echo $CodeTVA;?></span><span style="font-style:normal;font-weight:normal;font-size:7pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<img style="position:absolute;top:3.26in;left:8.09in;width:0.66in;height:0.30in" src="OutDocument/ci_20.png" />
<div style="position:absolute;top:3.31in;left:8.3in;width:0.38in;line-height:0.12in;"><span style="font-style:normal;font-weight:normal;font-size:7pt;font-family:Helvetica;color:#000000"><?php echo $Montant;?></span><span style="font-style:normal;font-weight:normal;font-size:7pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:3.61in;left:0.69in;width:0.73in;line-height:0.12in;"><span style="font-style:italic;font-weight:normal;font-size:7pt;font-family:Helvetica;color:#000000">Garantie 2 ans</span><span style="font-style:italic;font-weight:normal;font-size:7pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<img style="position:absolute;top:2.90in;left:0.38in;width:8.38in;height:0.88in" src="OutDocument/ci_21.png" />
<div style="position:absolute;top:5.54in;left:0.42in;width:2.97in;line-height:0.14in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Helvetica;color:#000000">  * Retrouvez tous nos services et conditions sur le site</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:5.80in;left:0.41in;width:7.57in;line-height:0.14in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Helvetica;color:#000000">Merci d&apos;avoir choisi CoreMansur !</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Helvetica;color:#000000">Pour effectuer un retour ou bénéficier de votre droit à la rétractation, connectez-vous directement sur votre compte client CoreMansur.</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:6.34in;left:0.41in;width:8.23in;line-height:0.14in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Helvetica;color:#000000">Conformément à l</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Arial;color:#000000">’</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Helvetica;color:#000000">article 8.1 de nos CGV, vous disposez d</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Arial;color:#000000">’</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Helvetica;color:#000000">un délai de rétractation de 14 jours calendaires pour retourner les produits ne vous convenant</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:6.48in;left:0.41in;width:7.83in;line-height:0.14in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Helvetica;color:#000000">pas. Ce délai court à compter du jour de la réception du produit, ou du dernier produit livré en cas de commandes de plusieurs produits vendus et</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Helvetica;color:#000000"> </span><br/><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Helvetica;color:#000000">expédiés par CoreMansur.</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Helvetica;color:#000000">Ce délai expiré, vous ne disposez plus de ce droit de rétractation.</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Helvetica;color:#000000">Lorsque ce délai expire un week-end, jour férié ou chômé, il est prolongé jusqu</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Arial;color:#000000">’</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Helvetica;color:#000000">au prochain jour ouvrable. Consultez nos CGV à l&apos;adresse</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:7.06in;left:0.41in;width:2.89in;line-height:0.14in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Helvetica;color:#000000">suivante : https://coremansur.000webhostapp.com/</span>
<span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:7.30in;left:0.41in;width:6.78in;line-height:0.14in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Helvetica;color:#000000">Les produits de déstockage ou d</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Arial;color:#000000">’</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Helvetica;color:#000000">occasion sont des produits qui ne sont plus vendus par les circuits classiques de distribution.</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Helvetica;color:#000000"> </span><br/><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Helvetica;color:#000000">Ces produits peuvent provenir de la rétractation d</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Arial;color:#000000">’</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Helvetica;color:#000000">un client, d</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Arial;color:#000000">’</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Helvetica;color:#000000">un retour SAV, de lots en fin de série ou d</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Arial;color:#000000">’</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Helvetica;color:#000000">invendus.</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:7.57in;left:0.41in;width:6.24in;line-height:0.14in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Helvetica;color:#000000">Ces produits connaissent une &quot; deuxième vie &quot; en étant vendus à des prix inférieurs à leur prix de vente traditionnel.</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:7.84in;left:0.41in;width:4.43in;line-height:0.14in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Helvetica;color:#000000">CoreMansur - 44-50 Av. du Capitaine Glarner - 93585 Saint-Ouen Cedex </span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Helvetica;color:#000000"> </span><br/><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Helvetica;color:#000000">RCS Bobigny B422 797 720 00030 - Code APE 4791B</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Helvetica;color:#000000">TVA intracommunautaire FR 26422797720 - S.A.S. au capital de 2 823 837 euros</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Helvetica;color:#000000"> </span><br/><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Helvetica;color:#000000">Intérêt de retard : Taux de base bancaire + 2 points</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:8.52in;left:0.41in;width:5.92in;line-height:0.14in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Helvetica;color:#000000">Notice officielle d</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Arial;color:#000000">’</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Helvetica;color:#000000">information sur la copie privée disponible à l</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Arial;color:#000000">’</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Helvetica;color:#000000">adresse : http://www.copieprivee.culture.gouv.fr</span>
<span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:8.66in;left:0.41in;width:8.10in;line-height:0.14in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Helvetica;color:#000000">Remboursement/exonération de la rémunération pour usage professionnel : Vous avez la possibilité de vous faire rembourser de la rémunération pour</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Helvetica;color:#000000"> </span><br/><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Helvetica;color:#000000">copie privée acquittée à l</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Arial;color:#000000">’</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Helvetica;color:#000000">occasion de votre achat</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN><br></div>


<div style="position:absolute;top:2.13in;left:5.41in;width:2.35in;line-height:0.14in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Helvetica;color:#000000"><?php echo $Nom; ?> </span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Helvetica;color:#000000"> </span><br/><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Helvetica;color:#000000"><?php echo $ADRESSE1; ?></span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Helvetica;color:#000000"><?php echo $ADRESSE2; ?></span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<img style="position:absolute;top:2.07in;left:5.37in;width:0.02in;height:0.76in" src="OutDocument/ci_29.png" />
<img style="position:absolute;top:2.80in;left:5.37in;width:3.39in;height:0.02in" src="OutDocument/ci_30.png" />
<img style="position:absolute;top:2.07in;left:8.74in;width:0.02in;height:0.76in" src="OutDocument/ci_31.png" />
<img style="position:absolute;top:1.84in;left:5.38in;width:3.37in;height:0.23in" src="OutDocument/ci_32.png" />
<div style="position:absolute;top:1.90in;left:5.41in;width:2.16in;line-height:0.18in;"><span style="font-style:normal;font-weight:bold;font-size:10pt;font-family:Helvetica;color:#000000">ADRESSE DE FACTURATION</span><span style="font-style:normal;font-weight:bold;font-size:10pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<img style="position:absolute;top:1.84in;left:5.37in;width:3.39in;height:0.02in" src="OutDocument/ci_33.png" />
<img style="position:absolute;top:1.83in;left:5.37in;width:0.02in;height:0.25in" src="OutDocument/ci_34.png" />
<img style="position:absolute;top:1.83in;left:8.74in;width:0.02in;height:0.25in" src="OutDocument/ci_35.png" />
<div style="position:absolute;top:5.28in;left:0.41in;width:2.46in;line-height:0.14in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Helvetica;color:#000000">Conditions de règlement : Paiement en Ligne</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<img style="position:absolute;top:5.25in;left:0.37in;width:8.33in;height:0.21in" src="OutDocument/ci_36.png" />
<div style="position:absolute;top:4.40in;left:6.59in;width:1.22in;line-height:0.14in;"><span style="font-style:normal;font-weight:bold;font-size:8pt;font-family:Helvetica;color:#000000">Total    HT ( Euros ) :</span><span style="font-style:normal;font-weight:bold;font-size:8pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:4.40in;left:8.20in;width:0.40in;line-height:0.14in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Helvetica;color:#000000">
	<?php echo $PUHT;?>
</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:4.60in;left:6.62in;width:1.19in;line-height:0.14in;"><span style="font-style:normal;font-weight:bold;font-size:8pt;font-family:Helvetica;color:#000000">Total TTC ( Euros ) :</span><span style="font-style:normal;font-weight:bold;font-size:8pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:4.60in;left:8.20in;width:0.40in;line-height:0.14in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Helvetica;color:#000000"><?php echo $TotalTTC;?></span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:4.80in;left:8.32in;width:0.27in;line-height:0.14in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Helvetica;color:#000000"><?php echo $EcoTaxe;?></span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:4.80in;left:6.07in;width:1.74in;line-height:0.14in;"><span style="font-style:normal;font-weight:bold;font-size:8pt;font-family:Helvetica;color:#000000">Dont Eco Taxe TTC ( Euros ) :</span><span style="font-style:normal;font-weight:bold;font-size:8pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<img style="position:absolute;top:4.40in;left:5.55in;width:0.02in;height:0.61in" src="OutDocument/ci_37.png" />
<img style="position:absolute;top:4.40in;left:0.39in;width:8.33in;height:0.61in" src="OutDocument/ci_38.png" />
<img style="position:absolute;top:3.82in;left:4.12in;width:1.07in;height:0.21in" src="OutDocument/ci_39.png" />
<div style="position:absolute;top:3.87in;left:4.15in;width:0.61in;line-height:0.14in;"><span style="font-style:normal;font-weight:bold;font-size:8pt;font-family:Helvetica;color:#000000">Code TVA</span><span style="font-style:normal;font-weight:bold;font-size:8pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<img style="position:absolute;top:3.82in;left:5.19in;width:1.24in;height:0.21in" src="OutDocument/ci_40.png" />
<div style="position:absolute;top:3.87in;left:5.22in;width:0.98in;line-height:0.14in;"><span style="font-style:normal;font-weight:bold;font-size:8pt;font-family:Helvetica;color:#000000">Base HT (Euros)</span><span style="font-style:normal;font-weight:bold;font-size:8pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<img style="position:absolute;top:3.82in;left:6.43in;width:1.07in;height:0.21in" src="OutDocument/ci_41.png" />
<div style="position:absolute;top:3.87in;left:6.46in;width:0.38in;line-height:0.14in;"><span style="font-style:normal;font-weight:bold;font-size:8pt;font-family:Helvetica;color:#000000">TVA%</span><span style="font-style:normal;font-weight:bold;font-size:8pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<img style="position:absolute;top:3.82in;left:7.50in;width:1.24in;height:0.21in" src="OutDocument/ci_42.png" />
<div style="position:absolute;top:3.87in;left:7.53in;width:1.21in;line-height:0.14in;"><span style="font-style:normal;font-weight:bold;font-size:8pt;font-family:Helvetica;color:#000000">Montant TVA(Euros)</span><span style="font-style:normal;font-weight:bold;font-size:8pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:4.08in;left:5.09in;width:0.10in;line-height:0.14in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Helvetica;color:#000000"><?php echo $CodeTVA;?></span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:4.08in;left:5.90in;width:0.40in;line-height:0.14in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Helvetica;color:#000000"><?php echo $PUHT;?></span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:4.08in;left:7.06in;width:0.44in;line-height:0.14in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Helvetica;color:#000000">
	<?php echo $TVA;?></span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:4.08in;left:8.25in;width:0.34in;line-height:0.14in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Helvetica;color:#000000">
	<?php echo $MontantTVA;?></span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<img style="position:absolute;top:3.82in;left:4.11in;width:4.63in;height:0.48in" src="OutDocument/ci_43.png" />
<div style="position:absolute;top:5.04in;left:6.26in;width:1.56in;line-height:0.14in;"><span style="font-style:normal;font-weight:bold;font-size:8pt;font-family:Helvetica;color:#000000">Net à payer TTC ( Euros ) :</span><span style="font-style:normal;font-weight:bold;font-size:8pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:5.04in;left:8.20in;width:0.40in;line-height:0.14in;"><span style="font-style:normal;font-weight:bold;font-size:8pt;font-family:Helvetica;color:#000000"><?php echo $Montant; ?></span><span style="font-style:normal;font-weight:bold;font-size:8pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<img style="position:absolute;top:0.56in;left:5.41in;width:3.34in;height:0.23in" src="OutDocument/ci_44.png" />
<div style="position:absolute;top:0.62in;left:6.71in;width:0.77in;line-height:0.18in;"><span style="font-style:normal;font-weight:bold;font-size:10pt;font-family:Helvetica;color:#000000">FACTURE</span><span style="font-style:normal;font-weight:bold;font-size:10pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<img style="position:absolute;top:0.55in;left:5.40in;width:3.36in;height:0.02in" src="OutDocument/ci_45.png" />
<img style="position:absolute;top:0.55in;left:5.40in;width:0.02in;height:0.25in" src="OutDocument/ci_46.png" />
<img style="position:absolute;top:0.55in;left:8.74in;width:0.02in;height:0.25in" src="OutDocument/ci_47.png" />

<div style="position:absolute;top:0.90in;left:6.64in;width:0.84in;line-height:0.14in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Helvetica;color:#000000">FACTURE N° :</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:1.33in;left:6.77in;width:0.70in;line-height:0.14in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Helvetica;color:#000000">CLIENT N° :</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:1.12in;left:6.50in;width:0.99in;line-height:0.14in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Helvetica;color:#000000">COMMANDE N° :</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:1.54in;left:6.87in;width:0.61in;line-height:0.14in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Helvetica;color:#000000">PAGE N° :</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:0.90in;left:8.13in;width:0.64in;line-height:0.14in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Helvetica;color:#000000">
	<?php echo $FACTURE;?></span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:1.12in;left:8.13in;width:0.71in;line-height:0.14in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Helvetica;color:#000000"><?php echo $COMMANDE;?></span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:1.34in;left:8.13in;width:0.57in;line-height:0.14in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Helvetica;color:#000000"><?php echo $CLIENT;?></span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:1.54in;left:8.54in;width:0.20in;line-height:0.14in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Helvetica;color:#000000">1/1</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Helvetica;color:#000000"> </span><br/></SPAN></div>

<img style="position:absolute;top:0.78in;left:5.40in;width:0.02in;height:0.97in" src="OutDocument/ci_48.png" />
<img style="position:absolute;top:1.74in;left:5.39in;width:3.36in;height:0.02in" src="OutDocument/ci_49.png" />
<img style="position:absolute;top:0.78in;left:8.74in;width:0.02in;height:0.97in" src="OutDocument/ci_50.png" />
<img style="position:absolute;top:0.59in;left:0.45in;width:1.85in;height:2.08in" src="OutDocument/logocore.png" />

</body>
</html>
